version: '3'

services:
  app:
    build: .
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 ./manage.py runserver 0.0.0.0:8000
