version: '3'

services:
  app:
    build: .
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 ./manage.py runserver 80:80
    networks:
      - Blog-network


  web:
    image: ubuntu
    container_name: ubuntu01
    # build: ./apache
    ports:
      - 80:80
    # restart:
    #   - always
    depends_on:
      - app
    networks:
      - Blog-network
networks:
  Blog-network:
    external: true
