# Generated by Django 3.2.5 on 2022-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
